# Generated by Django 4.1 on 2024-02-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='ors_college',
        ),
        migrations.AlterModelTable(
            name='course',
            table='ors_course',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='ors_faculty',
        ),
        migrations.AlterModelTable(
            name='marksheet',
            table='ors_marksheet',
        ),
        migrations.AlterModelTable(
            name='student',
            table='ors_student',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='ors_subject',
        ),
        migrations.AlterModelTable(
            name='timetable',
            table='ors_timetable',
        ),
    ]
